name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo xcode-select -s /Applications/Xcode_12.app/Contents/Developer
        swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage
    - name: Convert code coverage
      run: xcrun llvm-cov export -format="lcov" -instr-profile=$(find .build -name default.profdata) $(find .build -name NDHpplePackageTests) > info.lcov
    - name: Codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        file: info.lcov
